// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-jFV2HGJ0NjknO7j_5q9jjDHqdYb3oBc',
    appId: '1:1086255110542:web:62cec92679bb1ddc4a2cdf',
    messagingSenderId: '1086255110542',
    projectId: 'studyguideapp-4a8bf',
    authDomain: 'studyguideapp-4a8bf.firebaseapp.com',
    storageBucket: 'studyguideapp-4a8bf.appspot.com',
    measurementId: 'G-YQ8098DMH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFd9V46g0uCuxGehupE48Mz6k4NdgxYlM',
    appId: '1:1086255110542:android:7726eeed5a9c0f0c4a2cdf',
    messagingSenderId: '1086255110542',
    projectId: 'studyguideapp-4a8bf',
    storageBucket: 'studyguideapp-4a8bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMKhsKtBXaZt008tOd9ZZ8j713c4CDdSE',
    appId: '1:1086255110542:ios:36b19609cf97eb684a2cdf',
    messagingSenderId: '1086255110542',
    projectId: 'studyguideapp-4a8bf',
    storageBucket: 'studyguideapp-4a8bf.appspot.com',
    iosBundleId: 'com.example.studyguideapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMKhsKtBXaZt008tOd9ZZ8j713c4CDdSE',
    appId: '1:1086255110542:ios:36b19609cf97eb684a2cdf',
    messagingSenderId: '1086255110542',
    projectId: 'studyguideapp-4a8bf',
    storageBucket: 'studyguideapp-4a8bf.appspot.com',
    iosBundleId: 'com.example.studyguideapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-jFV2HGJ0NjknO7j_5q9jjDHqdYb3oBc',
    appId: '1:1086255110542:web:9cca0078e01407bb4a2cdf',
    messagingSenderId: '1086255110542',
    projectId: 'studyguideapp-4a8bf',
    authDomain: 'studyguideapp-4a8bf.firebaseapp.com',
    storageBucket: 'studyguideapp-4a8bf.appspot.com',
    measurementId: 'G-4VJEVHGQHW',
  );
}
